### PR TITLE
Make cli compatible with podman-compose

### LINKED ISSUE #138: Fails to build on Debian 12 with podman
```__  __   _                         ____                   _   _____         _             _          
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___ 
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|
                                                                                                       
The application designed to assist landlords in managing their properties and rentals

? Have you created a mailgun account for sending emails 
(https://www.mailgun.com/)? No
? Enter the URL to access the landlord front-end: http://localhost:8080/landlord

? Enter the URL to access the tenant front-end (it should share the same domain 
and port as the landlord front-end URL): http://localhost:8080/tenant
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

Using podman and docker-compose on debian 12

```
$ docker -v
Docker version 20.10.24+dfsg1, build 297e128
$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

### PR DESCRIPTION
**Pull request by zeronounours**
Add support to different compose engines:

- `docker-compose` (for older docker versions which does not have `compose` plugin)
- `podman-compose`
- `podman` with `compose` plugin

Feel free to recompile binaries for security concerns.

From the tests I made, removal of `extra_hosts` seems not to be breaking anything. However, I'm still not sure of where the backend of landlord nextjs is making call the API.

Fix #138

### CODE REVIEW

**Comment by camelaissani** [comment]
@zeronounours I just reviewed your PR. It looks good thanks :+1: 
I'm gonna rebuild the executables and test all that.

File: cli/src/commands.js [hunk 1]
```diff
@@ -94,7 +97,8 @@ async function dev() {
   initDirectories();
 
   await runCompose(
-    ['up', '--build', '--force-recreate', '--remove-orphans', '--no-color'],
+    'start',
```
Comment (camelaissani) [inline cli/src/commands.js:100]: Issue here should be 'dev'

File: cli/src/utils.js [hunk 2]
```diff
@@ -93,8 +94,61 @@ async function runCommand(cmd, parameters = [], options = {}) {
...
+  if (await which('podman', { nothrow: true }))
+    return ['podman', 'compose']
+
+  throw new Error('Cannot find a valid runtime to run containers');
+}
+
+const runComposeActions = {
+  'docker': {
+    start: ['up', '--build', '--force-recreate', '--remove-orphans', '--no-color'],
+    build: ['build', '--no-cache', '--force-rm'],
```
Comment (camelaissani) [inline cli/src/utils.js:117]: 'dev' action is missing here as well
'start' should not have `--build` option only 'dev' have it

File: cli/src/utils.js [hunk 3]
```diff
@@ -93,8 +94,61 @@ async function runCommand(cmd, parameters = [], options = {}) {
...
+  if (await which('podman-compose', { nothrow: true }))
+    return ['podman-compose']
+
+  if (await which('podman', { nothrow: true }))
+    return ['podman', 'compose']
+
+  throw new Error('Cannot find a valid runtime to run containers');
+}
+
+const runComposeActions = {
```
Comment (camelaissani) [inline cli/src/utils.js:114]: Wdyt about merging 'docker'/'docker-compose' and 'podman'/'podman-compose'. The compose actions are the same. Do you think they might diverge in the future?

Comment (zeronounours) [reply cli/src/utils.js:114]: Yes, I think it might.
Actually, docker-compose is deprecated and won't be updated anymore. I've added it for compatibility reasons with people who still have an old version of docker. Docker compose is a go rewrite of docker-compose and it will continue to live apart from it.
For podman/podman-compose i doubt it will differ for now. Podman compose is just a wrapper around docker-compose or podman-compose

**Comment by zeronounours** [comment]
In this new version, I've fix the `dev` command. I didn't notice the argument diff.

I've also modified the way compose arguments are retrieved with a switch case. This way, it is still possible to easily update actions for `docker-compose` and `podman-compose` if they end up being different

**Comment by camelaissani** [comment]
@zeronounours all good now thanks again

**Review by camelaissani — APPROVED** [review]
